export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const CARD_REQUEST = 'CARD_REQUEST'
export const DECK_REQUEST = 'DECK_REQUEST'

export const CREATE_CARD_SUCCESS = 'CREATE_CARD_SUCCESS'
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS'
export const UPDATE_CARD_SUCCESS = 'UPDATE_CARD_SUCCESS'
export const FETCH_CARD_SUCCESS = 'FETCH_CARD_SUCCESS'
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS'

export const CREATE_DECK_SUCCESS = 'CREATE_DECK_SUCCESS'
export const DELETE_DECK_SUCCESS = 'DELETE_DECK_SUCCESS'
export const UPDATE_DECK_SUCCESS = 'UPDATE_DECK_SUCCESS'
export const FETCH_DECK_SUCCESS = 'FETCH_DECK_SUCCESS'
export const FETCH_DECKS_SUCCESS = 'FETCH_DECKS_SUCCESS'